PROGRAM ValueOfVariables(INPUT, OUTPUT);
USES DOS;
BEGIN{ValueOfVariables}
  WRITELN(GetEnv('REQUEST_METHOD'));
  WRITELN(GetEnv('QUERY_STRING'));
  WRITELN(GetEnv('CONTENT_LENGTH'));
  WRITELN(GetEnv('HTTP_USER_AGENT'));
  WRITELN(GetEnv('HTTP_HOST'));
  WRITELN
END.{ValueOfVariables}
